### ISSUE TITLE
showing/hiding series bar rect on y axis not configurable via property

### ISSUE THREAD

**Issue by learner1024** [PredixDev/px-vis-xy-chart#11]
Hello px-vis-xy-chart team

first of all this is brilliant work and very useful. This issue is just two bit issue.

when we try to render minimal render XY chart, i.e. only config x axis, y axis, set chart data, simple default tooltip, we observed that y axis has rect drawn by d3 code with dimensions (15,2)

This is probably something like legend for y axis. Issue is, by this can not be configured by dev for y axis. 
I looked into code and found that x axis has prevent-series-bar and y axis doesnt. I have made changes to it in forked repo and exposed couple more properties, it would be nice if you can have look at that.

**Comment by nonmetalhail** [comment]
Hi, thanks. I mentioned this in the PR, but I'll reiterate here should others have similar questions. 

You can config all the axes properties via the xAxisCong and yAxisConfig property. For example, to enable the series bar on the x-axis-config:

```
x-axis-config='{ "preventSeriesBar": true }'
```

**Comment by learner1024** [comment]
Hi,
Yes, this x-axis-config setting works and I agree its the simplest solution to problem. again, thanks a lot!
I had gone through documentation to find suitable way but somehow it seems I missed this.

Regards,
sandeep
