### ISSUE TITLE
chartExtents mis-calculation

### ISSUE THREAD

**Issue by jimdefrisco** [PredixDev/px-vis-xy-chart#14]
Benoit - here are the details regarding the chartExtents issue we chatted about yesterday. I will try to put together a small codepen example when I have some time. The workaround of calculating the chartExtents ourselves is working fine for now.

## Expected behavior and actual behavior:
Our use case:
- plotting multiple series, each one represents a distinct timespan
- each series plots the same pair of tags, but with different timestamps (the 3rd dimension)
- we set chartExtents to 'dynamic' for all dimensions
- we set the timeDomain to the px-vis-nav object to the aggregate time period (includes all series timespans), this is getting correctly set in the chart component.

Expected: the chart would properly calculate the chart extents to include all the data passed
Actual: chart extents are calculated incorrectly, showing only a subset of the full dataset.

## Steps to reproduce the problem:
- create a couple of series with chart data that includes a different range of timestamps for each series. I'll attach some sample data for our fail case.
- set properties on the component as described in the above use case
- chart extents are not calculated correctly, resulting in a subset of the data shown.

[xy-extent-bug.json.zip](https://github.com/PredixDev/px-vis-xy-chart/files/1011993/xy-extent-bug.json.zip)

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
component: v1.1.1
browser: chrome
os: mac OSX El Capitan (v10.11.6)
hardware: Macbook Pro

**Comment by nonmetalhail** [comment]
Fixed; will be released with the next vis minor release
