### ISSUE TITLE
Tooltip is enabled even on out of scope points on zoom in.

### ISSUE THREAD

**Issue by fsevak** [PredixDev/px-vis-xy-chart#16]
We have a dashboard having 2 widgets one of them having  px-vis-xy-chart.
We have a functionality send/recieve, where one widgets sends some data and other receives that data and plots it on px-vis-xy-chart.
	
On recieving data from other widget and zooming in on px-vis-xy-chart , points which are not within the x and y axis are hidden. But when hovered outside the widget or outside chart section tooltip comes up for the hidden points.

Can you provide the functionality to hide the tooltip for points which are not within the x and y axis?
![tooltip](https://user-images.githubusercontent.com/24793520/26925778-b590687c-4c68-11e7-9fd3-a6cc50a39fef.PNG)

**Comment by nonmetalhail** [comment]
Same cause as issue #4
