### ISSUE TITLE
Demo issues

### ISSUE THREAD

**Issue by nonmetalhail** [PredixDev/px-vis-xy-chart#21]
- [ ] remove height from container
- [ ] navigator is wonky

**Comment by Deepa-Nayak** [comment]
- [ ] unable to hide slider
- [ ] Graph is loaded outside expected area
- [ ] Graph data disappears on zooming
- [ ] Unable to position Y-Axis to the right with setting "side":"right"
Please refer the attached image
![image](https://user-images.githubusercontent.com/31760318/39347703-b74b07ce-4a11-11e8-8be1-28b178ed5e98.png)
