### ISSUE TITLE
No padding between axis label and color legend bar

### ISSUE THREAD

**Issue by Rmohan06** [PredixDev/px-vis-xy-chart#6]
Should have a 3px space. Right now the first color bar sits directly next to the label.

<img width="161" alt="screen shot 2016-10-04 at 9 46 21 am" src="https://cloud.githubusercontent.com/assets/6842019/19083602/b264c7e2-8a17-11e6-81fc-f7ae3357116c.png">

**Comment by benoitjchevalier** [comment]
fixed
