### ISSUE TITLE
Adding a trendline series should not require date

### ISSUE THREAD

**Issue by nonmetalhail** [PredixDev/px-vis-xy-chart#7]
If date is specified to allow the navigator to limit the data displayed, date is then required for all series on the chart. You should be able to still have date as an optional argument on which to select. This change would then support adding a series as a trendline that will always be present on the chart and not be erased as the navigator is brushed.

**Comment by benoitjchevalier** [comment]
fixed by https://github.com/PredixDev/px-vis/pull/57
