### ISSUE TITLE
Resizing the xy-chart component increases it's size.

### ISSUE THREAD

**Issue by rupeshambati** [PredixDev/px-vis-xy-chart#9]
Attached is the behaviour.

https://ge.box.com/s/t2fvx7604qbw6rmqck5y2mmmua8kbgoa

**Comment by benoitjchevalier** [comment]
Thanks for the feedback, we're aware of the issue and hope to have it fixed in the next major version where the chart horizontal and vertical position can be dev set

**Comment by benoitjchevalier** [comment]
Now fixed in 0.2.17
